import type { Staff, Shift, Role } from './types';

export const roles: Role[] = [
  { id: 'role-1', name: 'LiveChat', requiredAgents: 3 },
  { id: 'role-2', name: 'Inbound', requiredAgents: 2 },
  { id: 'role-3', name: 'Outbound', requiredAgents: 1 },
];

export const staff: Staff[] = [
  {
    id: 'staff-1',
    name: 'Alex Ray',
    avatar: 'https://placehold.co/40x40/3498DB/FFFFFF.png',
    skills: ['Customer Support', 'Technical Troubleshooting', 'Sales', 'LiveChat'],
    availability: 'Prefers weekdays',
  },
  {
    id: 'staff-2',
    name: 'Jordan Shaw',
    avatar: 'https://placehold.co/40x40/2980B9/FFFFFF.png',
    skills: ['Data Analysis', 'Reporting', 'System Administration', 'Outbound'],
    availability: 'Prefers Mon-Wed',
  },
  {
    id: 'staff-3',
    name: 'Casey Lee',
    avatar: 'https://placehold.co/40x40/EBF5FB/222222.png',
    skills: ['Customer Support', 'Billing', 'Inbound', 'LiveChat'],
    availability: 'Prefers weekends',
  },
  {
    id: 'staff-4',
    name: 'Morgan Pat',
    avatar: 'https://placehold.co/40x40/222222/FFFFFF.png',
    skills: ['Technical Troubleshooting', 'System Administration', 'Outbound'],
    availability: 'Any day',
  },
  {
    id: 'staff-5',
    name: 'Taylor Green',
    avatar: 'https://placehold.co/40x40/58D68D/FFFFFF.png',
    skills: ['LiveChat', 'Customer Support', 'Inbound'],
    availability: 'Not available on weekends',
  },
  {
    id: 'staff-6',
    name: 'Jamie Rivera',
    avatar: 'https://placehold.co/40x40/F5B041/FFFFFF.png',
    skills: ['Inbound', 'Sales', 'Customer Support'],
    availability: 'Prefers morning shifts',
  },
  {
    id: 'staff-7',
    name: 'Drew Kim',
    avatar: 'https://placehold.co/40x40/AF7AC5/FFFFFF.png',
    skills: ['Outbound', 'Data Analysis'],
    availability: 'Prefers evening shifts',
  },
  {
    id: 'staff-8',
    name: 'Skyler Morgan',
    avatar: 'https://placehold.co/40x40/EC7063/FFFFFF.png',
    skills: ['LiveChat', 'Technical Troubleshooting'],
    availability: 'Flexible',
  },
  {
    id: 'staff-9',
    name: 'Pat Brooks',
    avatar: 'https://placehold.co/40x40/5DADE2/FFFFFF.png',
    skills: ['Inbound', 'Billing'],
    availability: 'Mon-Fri',
  },
  {
    id: 'staff-10',
    name: 'Chris Collins',
    avatar: 'https://placehold.co/40x40/48C9B0/FFFFFF.png',
    skills: ['LiveChat', 'Customer Support'],
    availability: 'Any day',
  },
  {
    id: 'staff-11',
    name: 'Sam Brooks',
    avatar: 'https://placehold.co/40x40/F7DC6F/222222.png',
    skills: ['Outbound', 'Sales'],
    availability: 'Weekend only',
  },
    {
    id: 'staff-12',
    name: 'Jesse Flores',
    avatar: 'https://placehold.co/40x40/E74C3C/FFFFFF.png',
    skills: ['Inbound', 'LiveChat', 'Technical Support'],
    availability: 'Any day',
  },
  {
    id: 'staff-13',
    name: 'Quinn Bailey',
    avatar: 'https://placehold.co/40x40/8E44AD/FFFFFF.png',
    skills: ['LiveChat', 'Customer Support'],
    availability: 'Flexible',
  }
];

// Initial shifts are empty, they will be generated by the AI
export const shifts: Shift[] = [];
